# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d93873620e405deb915970c2dacd5c85"
name = "Open Ai Ads Pixel"
application_url = "https://openAI-ads-pixel.test"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customer_events,read_products,write_products,read_themes,write_themes,read_pixels,write_pixels"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ "https://openAI-ads-pixel.test/authenticate" ]

[webhooks]
api_version = "2026-07"
