# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "be743dbff20137425817beebf4d1fa06"
name = "OpenAI Ads Pixel"
application_url = "https://openai-ads-pixel.test"
embedded = true

[webhooks]
api_version = "2026-01"

  [[webhooks.subscriptions]]
  uri = "/webhook/app-uninstalled"
  topics = [ "app/uninstalled" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customer_events,read_products,write_products,read_themes,write_themes,read_pixels,write_pixels"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://openai-ads-pixel.test/authenticate"
]