# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9a5c6f0d42117559956e1fec025fc24b"
name = "Open Ai Ads Pixel"
application_url = "https://openAI-ads-pixel.test"
embedded = true

[webhooks]
api_version = "2026-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customer_events,read_products,write_products,read_themes,write_themes,read_pixels,write_pixels"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ "https://openAI-ads-pixel.test/authenticate" ]
