export const CSV_HEADERS = {
    id: "ID",
    product_id: "Product ID",
    product_title: "Product Title",
    product_handle: "Product Handle",
    type: "Type",
    image_url: "Image URL",
    text: "Text",
    font_family: "Font Family",
    font_size: "Font Size",
    font_color: "Font Color",
    bg_color: "Background Color",
    opacity: "Opacity",
    rotation: "Rotation",
    padding_top: "Padding Top",
    padding_right: "Padding Right",
    padding_bottom: "Padding Bottom",
    padding_left: "Padding Left",
    text_align: "Text Align",
    position: "Position",
    status: "Status",
    scale_in_collection: "Scale In Collection",
    scale_in_product: "Scale In Product",
    scale_in_search: "Scale In Search",
    display_in_collection: "Display In Collection",
    display_in_product: "Display In Product",
    display_in_search: "Display In Search"
};
